spring :
  datasource:
    url: jdbc:h2:tcp://localhost/~/sh
    username: sa
    password:
    driver-class-name: org.h2.Driver
  messages:
    basename: errors
  jwt:
    secret: 11111111111111111111111111111111111111111111111111111111111111awwererere


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace