spring :
  datasource:
    url: jdbc:h2:tcp://localhost/~/sh
    username: sa
    password:
    driver-class-name: org.h2.Driver
  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie